name: text_table
description: Renders style-able flex ascii tables.
version: 4.0.3
homepage: https://github.com/desktop-dart/text_table

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  characters: ^1.2.1
  collection: ^1.17.0

dev_dependencies:
  test: ^1.21.6
