name: text_table
description: Renders style-able flex ascii tables.
version: 2.6.0
homepage: https://github.com/desktop-dart/text_table
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.14.3
