name: text_table
description: Renders style-able flex ascii tables.
version: 4.0.0
homepage: https://github.com/desktop-dart/text_table

environment:
  sdk: '>=2.15.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.14.3
